sudo: required
service:
  - docker

before_install:
  - docker build -t sahngju/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true sahngju/docker-react npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "ap-northeast-2"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-ap-northeast-2-874563968737"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
